image:
  repository: poovarasan7cueverz/helm-backend
  tag: "latest"

service:
  type: NodePort
  port: 8000

mysql:
  host: my-mysql.default.svc.cluster.local
  database: flaskreact
  user: helmdb
  password: Team1234#

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

IAM_ROLE_URN: arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_IAM_ROLE_NAME>
