apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      containers:
        - name: {{ .Release.Name }}-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_SERVICE_HOST
              value: "{{ .Values.backendService.host }}"
            - name: BACKEND_SERVICE_PORT
              value: "{{ .Values.backendService.port }}"
