apiVersion: v1
kind: Service
metadata:
  name: frontend-test-ui-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: frontend-test-ui
